services:
  omada:
    container_name: omada
    environment:
      MANAGE_HTTP_PORT: "8088"
      MANAGE_HTTPS_PORT: "8043"
      PORTAL_HTTP_PORT: "8888"
      PORTAL_HTTPS_PORT: "8843"
      SHOW_MONGODB_LOGS: "false"
      SHOW_SERVER_LOGS: "true"
      TZ: America/Costa_Rica
    image: mbentley/omada-controller:6.0
    mem_limit: "4194304000"
    mem_reservation: "3670016000"
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/mzuniga/homelab/omada/data
        target: /opt/tplink/EAPController/data
        bind: {}
      - type: bind
        source: /home/mzuniga/homelab/omada/logs
        target: /opt/tplink/EAPController/logs
        bind: {}
