services:
  owntracks-recorder:
    image: owntracks/recorder:latest
    container_name: owntracks-recorder
    restart: unless-stopped
    ports:
      - "8083:8083"
    volumes:
      - ./store:/store
    environment:
      - OTR_STORAGEDIR=/store
      - OTR_HOST=192.168.10.56
      - OTR_PORT=1883
      - OTR_USER=mqtt
      - OTR_PASS=corderitos
      - OTR_HTTPHOST=0.0.0.0
      - OTR_HTTPPORT=8083
      - OTR_CLIENTID=owntracks-recorder-main
      - OTR_KEEPALIVE=120
      - OTR_QOS=1
